name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_IMAGE_NAME: mern-from-scratch-app
      REACT_APP_REGISTRY: fmteqniqly.azurecr.io
      REACT_APP_WEBAPP_NAME: mern-from-scratch-app
      REACT_APP_RESOURCE_GROUP: mern-from-scratch-rg

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker
        run: |
          cd /proshop/app
          docker build -t $REACT_APP_IMAGE_NAME .
          docker tag $REACT_APP_IMAGE_NAME $REACT_APP_REGISTRY/$REACT_APP_IMAGE_NAME:latest
          docker login $REACT_APP_REGISTRY -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        run: |
          docker push $REACT_APP_REGISTRY/$REACT_APP_IMAGE_NAME:latest

      # - name: Update Azure Web App with the new container image
      #   run: |
      #     az webapp config container set --name $REACT_APP_WEBAPP_NAME --resource-group $REACT_APP_RESOURCE_GROUP --docker-custom-image-name $REACT_APP_REGISTRY/$REACT_APP_IMAGE_NAME:latest --docker-registry-server-url "https://$REACT_APP_REGISTRY" --docker-registry-server-user ${{ secrets.AZURE_REGISTRY_USERNAME }} --docker-registry-server-password ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # - name: Set environment variables for your app (if needed)
      #   run: |
      #     az webapp config appsettings set --resource-group $REACT_APP_RESOURCE_GROUP --name $REACT_APP_WEBAPP_NAME --settings REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}

      - name: Deployed successfully!
        run: echo 'The React app has been deployed to Azure Web App.'
